### ISSUE TITLE
Make compendium entry URLs static

### ISSUE THREAD

**Issue by kernelmethod** [The-Encryption-Compendium/TECv2#17]
The URL for a compendium entry currently changes between updates to the site. It should be made static so that users can share URLs with one another and have those URLs remain the same over an extended period of time.

**Comment by dkg** [comment]
This seems like a good idea.  I'd help with it but i don't really understand the zotero db used for this compendium or the tooling around it very well.

I note that https://encryptioncompendium.org/ appears to use different URLs for the entries than https://the-encryption-compendium.github.io/ -- The code i'm looking at in this repo (in particular, `deploy_tools/generate_compendium.py`) seems to produce files that align with the github.io variant, so i'm not sure how the other code is being generated.

I see three alternate reasonable ways of approaching this (there are probably more):

- if the zotero db has a canonical shape as an ordered list (as `data.bib` appears to have), and new items are appended to that list, then just associate each item with its position in the list.  the URL is then derived from the number associated with the item (e.g. `https://encryptioncompendium.org/entry/7`).  This might be problematic if items are ever removed from the zotero db -- so you'd need to think about how to leave "tombstone" markers for deleted items.    And it would definitely be bad if items are ever reordered in the list.  This seems to be how https://the-encryption-compendium.github.io is doing things.
- if the zotero db allows you to associate a new field with each db entry, then just add a new field that is a "shortname" for each article.  this requires a bit of up-front work (assigning shortnames for each item already in the db) and some sort of consistency check that ensures that (a) all entries have a shortname, and (b) the shortnames are unique.  Then the URL for each article is derived from the shortname. (e.g. `https://encryptioncompendium.org/entry/keys-under-doormats`)
- if neither of these are an option, you could instead derive the URL for each item from a reasonably strong cryptographic digest of an unlikely-to-change attribute (or collection of attributes) about the article.  For example, you could use the first 40 bits of the sha256 digest of the article title as represented in UTF-8.  the URL for each article would then be derived from this 10-digit hex string.(e.g. `https://encryptioncompendium.org/entry/f2ca1bb6c7`)  This could be a problem if the selected attribute (or attributes) ends up changing (e.g. if an article changes its name) or if two articles have identical names.  To defend against the first problem, you could provide a list of aliases for each article, so that at least an article URL derived from the earlier revision of the attribute could map to (or HTTP redirect) to the final variant.   If you have two articles with the same name, perhaps you could include some other distinguishing field (year of publication) to avoid a collision.


https://encryptioncompendium.org appears to use some combination of the latter two approaches, with some kind of hex identifier appended to a simplified shortname.  I can't find the code that would generate this, so i can't evalutate how effective it is.

**Comment by kernelmethod** [comment]
Yeah, apologies -- the stuff that's currently on [encryptioncompendium.org](https://encryptioncompendium.org) comes from the `distinct_compendium_urls` branch, which I really ought to have merged into `master` a few months ago (especially before pushing it to the site) but didn't. I've opened #30 to get that branch merged in, so hopefully once that's done the GitHub Pages version and the official version should match up.

The updated version of `generate_compendium.py` is a little combination of your second and third ideas, actually. I didn't go with the first idea because of the exact problems you mentioned. Items are occasionally removed from the database, but the bigger issue is that Zotero sorts by last modified date. I could try leaving tombstone markers, or find a different way to enforce a consistent ordering, but that's difficult to do while making the process for building compendium entries stateless.

The way that the updated script works is that I generate a slug of the title with [slugify](https://pypi.org/project/python-slugify/) and truncate it after 50 characters. That leaves an additional issue -- what will happen if two articles have identical titles/slugs (which isn't infeasible since a lot of entries have formulaic titles like "Coalition letter to ...") -- so I went ahead and appended the first 32 bits of the SHA-256 hash of the entry (as a JSON string) to the slug. The meat of that code is here: https://github.com/The-Encryption-Compendium/TECv2/blob/8f307db860904b5a8dc6b7a805eb4c27cfaea3ba/deploy_tools/generate_compendium.py#L153-L172

There are still some lingering issues, e.g. the hash changing if the entry changes, but I think the problem is now mostly fixed (or at least, it's improved over where it was before)!

**Comment by dkg** [comment]
given the relatively small size of the database, what about just embedding a manually-chosen slug to each entry, and then adding a consistency check that each entry's slug is unique?  that would avoid concerns about the URL changing when the entry changes (or if `json.dumps` happens to produce non-reproducible output, which seems plausible, e.g. if the `sort_keys` option to `json.dumps` were to default to `true` in a future version)
