### ISSUE TITLE
Coalition letters to Obama list Obama as a "contributor"

### ISSUE THREAD

**Issue by dkg** [The-Encryption-Compendium/TECv2#56]
Looking in `data.bib`, i see several entries with id of `obama_coalition_*`, each of which lists:

```
collaborator = {Obama, Barack},
```

Since Obama was the recipient of the letter, he was not really a collaborator in writing it.  That's probably incorrect.

**Comment by dkg** [comment]
Similar problems exist with a few open letters to Mark Zuckerberg

**Comment by kernelmethod** [comment]
Yeah, it's a bit strange, Zotero has a key called "recipient" that gets converted to "collaborator" when you export to BibTeX (perhaps because BibTeX doesn't support a similar `recipient` field, at least AFAIK). So e.g. for the several coalition letters to Obama, he is recorded in Zotero as the recipient of the letter but then recorded as a collaborator in `data.bib`.

Unfortunately I'm not sure there's much that could be done to fix this, but I don't think that the "collaborator" field is used anywhere in the compendium generation script, and I don't anticipate that it'll need to be used soon.

**Comment by dkg** [comment]
ok, makes sense.  sounds like there's no risk that this will leak to the public-facing compendium, so i'll close this issue.
